repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: previews
        name: Generate Preview to data.hpp
        entry: scripts/generate_previews.sh
        language: script
        pass_filenames: false
