//=============================================================================
//
// file :        MoenchControlStateMachine.cpp
//
// description : State machine file for the MoenchControl class
//
// project :     Tango device for control of MOENCH detector
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "MoenchControl.h"
#include "sls/sls_detector_defs.h"

//================================================================
//  States  |  Description
//================================================================

namespace MoenchControl_ns {
//=================================================
//		Attributes Allowed Methods
//=================================================
bool MoenchControl::is_detector_read_write_allowed() {
  auto detector_status = detector_ptr->getDetectorStatus().front();
  return (detector_status == slsDetectorDefs::runStatus::IDLE
          || detector_status == slsDetectorDefs::runStatus::RUN_FINISHED
          || detector_status == slsDetectorDefs::runStatus::STOPPED);
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_exposure_allowed()
 * Description:  Execution allowed for exposure attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_exposure_allowed(TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for exposure attribute in Write access.

  //	Not any excluded states for exposure attribute in read access.
  return is_detector_read_write_allowed();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_delay_allowed()
 * Description:  Execution allowed for delay attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_delay_allowed(TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for delay attribute in Write access.

  //	Not any excluded states for delay attribute in read access.
  return is_detector_read_write_allowed();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_timing_mode_allowed()
 * Description:  Execution allowed for timing_mode attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_timing_mode_allowed(
    TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for timing_mode attribute in Write access.

  //	Not any excluded states for timing_mode attribute in read access.
  return is_detector_read_write_allowed();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_triggers_allowed()
 * Description:  Execution allowed for triggers attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_triggers_allowed(TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for triggers attribute in Write access.

  //	Not any excluded states for triggers attribute in read access.
  return is_detector_read_write_allowed();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_frames_allowed()
 * Description:  Execution allowed for frames attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_frames_allowed(TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for frames attribute in Write access.

  //	Not any excluded states for frames attribute in read access.
  return is_detector_read_write_allowed();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_high_voltage_allowed()
 * Description:  Execution allowed for high_voltage attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_high_voltage_allowed(
    TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for high_voltage attribute in Write access.

  //	Not any excluded states for high_voltage attribute in read access.
  return is_detector_read_write_allowed();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_period_allowed()
 * Description:  Execution allowed for period attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_period_allowed(TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for period attribute in Write access.

  //	Not any excluded states for period attribute in read access.
  return is_detector_read_write_allowed();
}

#if SLS_MAJOR_VERSION < 9
//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_zmq_rx_ip_allowed()
 * Description:  Execution allowed for zmq_rx_ip attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_zmq_rx_ip_allowed(
    TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for zmq_rx_ip attribute in Write access.

  //	Not any excluded states for zmq_rx_ip attribute in read access.
  return is_detector_read_write_allowed();
}
#endif

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_zmq_rx_port_allowed()
 * Description:  Execution allowed for zmq_rx_port attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_zmq_rx_port_allowed(
    TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for zmq_rx_port attribute in Write access.

  //	Not any excluded states for zmq_rx_port attribute in read access.
  return is_detector_read_write_allowed();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_rx_discard_policy_allowed()
 * Description:  Execution allowed for rx_discard_policy attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_rx_discard_policy_allowed(
    TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for rx_discard_policy attribute in Write
  // access.

  //	Not any excluded states for rx_discard_policy attribute in read access.
  return is_detector_read_write_allowed();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_rx_hostname_allowed()
 * Description:  Execution allowed for rx_hostname attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_rx_hostname_allowed(
    TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for rx_hostname attribute in Write access.

  //	Not any excluded states for rx_hostname attribute in read access.
  return is_detector_read_write_allowed();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_rx_tcp_port_allowed()
 * Description:  Execution allowed for rx_tcp_port attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_rx_tcp_port_allowed(
    TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for rx_tcp_port attribute in Write access.

  //	Not any excluded states for rx_tcp_port attribute in read access.
  return is_detector_read_write_allowed();
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_detector_status_allowed()
 * Description:  Execution allowed for detector_status attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_detector_status_allowed(
    TANGO_UNUSED(Tango::AttReqType type)) {

  //	Not any excluded states for detector_status attribute in read access.
  return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_rx_zmq_data_stream_allowed()
 * Description:  Execution allowed for rx_zmq_data_stream attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_rx_zmq_data_stream_allowed(
    TANGO_UNUSED(Tango::AttReqType type)) {
  //	Not any excluded states for rx_zmq_data_stream attribute in Write
  // access.

  //	Not any excluded states for rx_zmq_data_stream attribute in read
  // access.
  return is_detector_read_write_allowed();
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_start_acquire_allowed()
 * Description:  Execution allowed for start_acquire attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_start_acquire_allowed(
    TANGO_UNUSED(const CORBA::Any &any)) {
  //	Not any excluded states for start_acquire command.
  return true;
}

//--------------------------------------------------------
/**
 *	Method      : MoenchControl::is_stop_acquire_allowed()
 * Description:  Execution allowed for stop_acquire attribute
 */
//--------------------------------------------------------
bool MoenchControl::is_stop_acquire_allowed(
    TANGO_UNUSED(const CORBA::Any &any)) {
  //	Not any excluded states for stop_acquire command.
  return true;
}

bool MoenchControl::is_triggers_left_allowed(
    TANGO_UNUSED(const Tango::AttReqType type)) {
  return true;
}

} //	End of namespace
