#!/bin/bash
# for all recursive .cpp and hpp files in tango-moenchzmq and tango-moenhcontrol apply clang-format

script_path=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# except data.hpp generated by generate_previews.sh
find "$script_path/../tango-moenchzmq" -type f -name "*.cpp" -o -name "*.hpp" ! -name "data.hpp" -exec clang-format -i {} \;
find "$script_path/../tango-moenchcontrol" -type f -name "*.cpp" -o -name "*.hpp" -exec clang-format -i {} \;
