name: Upload coverage report

on:
  workflow_run:
    workflows: ["Build and test Ubuntu Linux"]
    types:
      - completed

jobs:
  coverage_report:
    name: Upload coverage report
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main') }}
    steps:
      - name: Download coverage data
        uses: actions/download-artifact@v4
        with:
          name: coverage-report-9.5.0-8.0.2

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          fail_ci_if_error: true
          codecov_yml_path: 'codecov.yml'
          token: ${{ secrets.CODECOV_TOKEN }}
